<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Timesheet extends \App\Entity\Timesheet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'hours_worked', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'template', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'worklogs'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'hours_worked', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'template', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Timesheet' . "\0" . 'worklogs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Timesheet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getWorklogs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorklogs', []);

        return parent::getWorklogs();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorklogs(\Doctrine\Common\Collections\Collection $worklogs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorklogs', [$worklogs]);

        return parent::setWorklogs($worklogs);
    }

    /**
     * {@inheritDoc}
     */
    public function addWorklog(\App\Entity\Worklog $worklog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWorklog', [$worklog]);

        return parent::addWorklog($worklog);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWorklog($worklog): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWorklog', [$worklog]);

        return parent::removeWorklog($worklog);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoursWorked(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoursWorked', []);

        return parent::getHoursWorked();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoursWorked(?float $hours_worked): \App\Entity\Timesheet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoursWorked', [$hours_worked]);

        return parent::setHoursWorked($hours_worked);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Entity\Users $user): \App\Entity\Timesheet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTimeInterface $date): \App\Entity\Timesheet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemplate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemplate', []);

        return parent::getTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemplate(?string $template): \App\Entity\Timesheet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemplate', [$template]);

        return parent::setTemplate($template);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?string $status): \App\Entity\Timesheet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

}
