<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container55K0Qn5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container55K0Qn5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container55K0Qn5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container55K0Qn5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container55K0Qn5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '55K0Qn5',
    'container.build_id' => '4f9061eb',
    'container.build_time' => 1557772255,
], __DIR__.\DIRECTORY_SEPARATOR.'Container55K0Qn5');
