<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFnrqxpF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFnrqxpF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFnrqxpF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFnrqxpF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFnrqxpF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FnrqxpF',
    'container.build_id' => 'cd0c8690',
    'container.build_time' => 1557591577,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFnrqxpF');
