<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDcrDNTW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDcrDNTW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDcrDNTW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDcrDNTW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDcrDNTW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DcrDNTW',
    'container.build_id' => '2201e687',
    'container.build_time' => 1557686898,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDcrDNTW');
